trigger:
  branches:
    include:
      - develop
      - feature/**
      - release/**
      - master
      - hotfix/**

pr:
  branches:
    include:
      - develop
      - master

pool:
  name: 'Default' # Use self-host agent pool named 'Default'

variables:
  dotNetVersion: 8.0.x
  solution: ./RichillCapital.SharedKernel.sln
  
resources:
  - repo: self

stages:
  - stage: DevelopmentStage
    displayName: Development stage 

    variables:
      buildConfiguration: Release 
      
    jobs:
      - job: DevelopmentJob
        displayName: Development job 

        steps:
          - task: UseDotNet@2
            displayName: Use .NET sdk $(dotNetVersion)

          - script: dotnet restore $(solution) --no-cache 
            displayName: Restore dependencies 

          - script: dotnet build $(solution) -c $(buildConfiguration) --no-restore 
            displayName: Build solution ($(buildConfiguration))

          - script: dotnet test $(solution) -c $(buildConfiguration) --no-build --no-restore
            displayName: Test 

  - stage: ReleaseStage
    displayName: Release stage

    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
    
    jobs:
      - job: ReleaseJob
        displayName: Release job

        variables:
          buildConfiguration: Release

        steps:
          - task: UseDotNet@2
            displayName: Use .NET sdk $(dotNetVersion)

          - task: PowerShell@2
            displayName: Generate release version 
            inputs:
              targetType: inline
              script: |
                Write-Host "Generating release version from branch: $(Build.SourceBranch)"

                $branchName = "$(Build.SourceBranchName)"
                Write-Host "##vso[task.setvariable variable=ReleaseVersion]$branchName"
                
                Write-Host "Generated Release Version: $branchName"
              
          - task: NuGetCommand@2
            displayName: Pack 
            inputs:
              command: pack
              packagesToPack: ./RichillCapital.SharedKernel.nuspec
              arguments: -NoDefaultExclude -OutputDirectory $(Build.ArtifactStagingDirectory)/artifacts -Properties Configuration=Release -Version $(ReleaseVersion) 
            
          - task: PublishPipelineArtifact@1
            displayName: Publish artifact 
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/artifacts
              artifact: RichillCapital.SharedKernel-$(buildConfiguration)-$(ReleaseVersion)
              publishLocation: pipeline

  - stage: ProductionStage
    displayName: Production stage 

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: ProductionJob
        displayName: Production job
        steps:
          - script: echo "Deploying to production..."
            displayName: Deploy to production                