trigger:
  branches:
    include:
      - develop
      - feature/**
      - release/**
      - master
      - hotfix/**

pr:
  branches:
    include:
      - develop
      - master

pool:
  name: 'Default' # Use self-host agent pool named 'Default'

variables:
  dotNetVersion: '8.0.x'
  solution: './RichillCapital.SharedKernel.sln'
  
resources:
  - repo: self

stages:
  - stage: BuildStage
    displayName: 'Build stage'
    jobs:
      - job: BuildJob
        displayName: 'Build job'

        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET sdk $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotNetVersion)'

          - script: dotnet restore --no-cache 
            displayName: 'Restore dependencies'

          - script: dotnet build --configuration Release --no-restore
            displayName: 'Build'

          - script: dotnet test --configuration Release --no-build --no-restore
            displayName: 'Run tests'

  - stage: ReleaseStage
    displayName: Release stage
    dependsOn: BuildStage
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))

    jobs:
      - job: ReleaseJob
        displayName: Release job

        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET sdk $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotNetVersion)'

          - script: dotnet restore --no-cache 
            displayName: 'Restore dependencies'
          
          - script: dotnet build --configuration Release --no-restore
            displayName: 'Build'
