name: .NET Cake Build

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x
  SOLUTION_FILE: ./RichillCapital.SharedKernel.sln
  CONFIGURATION: Release
  NUGET_SOURCE: https://api.nuget.org/v3/index.json
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run the Cake script
      uses: cake-build/cake-action@v2
      with:
        script-path: ./build.cake
        target: Default
        arguments: --configuration=${{ env.CONFIGURATION }} --source=${{ env.NUGET_SOURCE }}