name: .NET Continuous Integration

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    ## Get tag version
    - name: Get tag version
      id: get_tag_version
      run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

    ## Set ./RichillCapital.SharedKernel.csproj version
    - name: Set ./RichillCapital.SharedKernel.csproj version
      run: dotnet build ./RichillCapital.SharedKernel.csproj -p:Version=${{ steps.get_tag_version.outputs.tag }}