name: .NET Continuous Integration

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    