name: .NET Continuous Integration

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev
env:
  ProjectPath: ./RichillCapital.SharedKernel.csproj
  CakeFilePath: ./build.cake
  Target: Default
  Configuration: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      id: nbgv

    - name: .NET Build and Tests
      uses: cake-build/cake-action@v2
      with:
        script-path: ${{ env.CakeFilePath }}
        target: ${{ env.Target }}
        verbosity: Diagnostic
        arguments: |
          configuration: ${{ env.Configuration }}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RichillCapital.Domain-${{ steps.nbgv.outputs.GitCommitIdShort }}-${{ env.Configuration }}
        path: ./artifacts          